### ISSUE TITLE
Links to play/tasks can be broken due to unescaped characters

### ISSUE THREAD

**Issue by dmsimard** [dmsimard/ara#1]
For example: The task "Ensure /etc/ssl/sensu exists" translates to "/task/Ensure%20/etc/ssl/sensu%20exists" which is broken.

Need to escape/unescape to prevent that from happening. (urllib.parse.quote)

**Comment by larsks** [comment]
```
>>> import urlparse
>>> urllib.quote('Ensure /etc/ssl/sensu exists', safe='')
'Ensure%20%2Fetc%2Fssl%2Fsensu%20exists'

```

**Comment by dmsimard** [comment]
This just doesn't play well with Flask from my tests. Even considering http://flask.pocoo.org/snippets/76/ because it can interpret slashes as part of the URL (or not).

We can bump into so many issues regarding encoding and decoding back, I've done away with "friendly" links and transitioned to UUIDs instead in https://github.com/dmsimard/ara/commit/389ead5f7aa4001ecdea446a30a7719bcdde7e8d.
