### ISSUE TITLE
Filter by roles ?

### ISSUE THREAD

**Issue by dmsimard** [dmsimard/ara#102]
Right now we have a way to filter by host -> playbook -> play -> task -> task_result.

Do we have a way to know if we're running inside of a role and record it as such ?
In a playbook, there is typically more roles involved than plays so there would be value IMO.

Example for purpose of putting it into pseudo writing:
I have a playbook that installs openstack .. but this playbook really leverages like 10 roles, one to setup keystone, one to setup mysql, and so on.

Maybe I'm just interested at looking for keystone stuff.

**Comment by larsks** [comment]
Ansible doesn't have any role-related callbacks right now (which is a problem with Ansible, but not something that we're going to solve here).

We differentiate tasks by the file in which they appear, so maybe we can present a list of files that are part of play, and then use that to present lists of tasks from a particular file.  We could populate file information for plays, as well -- it's not available in the callback, but we can probably infer it by taking the file from the first task in a play and using that to populate the play's file.

**Comment by dmsimard** [comment]
Safe to say this was addressed by the filter by file feature that is being worked on.
