### ISSUE TITLE
Are hosts globally unique?

### ISSUE THREAD

**Issue by larsks** [dmsimard/ara#103]
Right now, we treat hosts as globally unique.  Regardless of how many playbooks you run, there will only ever be a single row in the `hosts` table for a host named `webserver`.  This makes sense *in general*, but isn't always going to be true.  Consider the case where I have one inventory that looks like this:

    webserver ansible_host=host000.region1.example.com

And I have another inventory file that looks like:

    webserver ansible_host=some-random-host.aws.amazon.com

Anytime I run a playbook pointing at either of these inventory files, it will overwrite the facts for the `webserver` host.   Furthermore, I may have inventory files that reference the same host but connect *as different users*, so that some of the facts may be different.

And even absent inventory files, if I run a playbook targeting `localhost` on more than one host and I am pointing at the same ARA database, I run into the same problem.

So:

- Do we care?
- If we care, how do we handle this?
- If we handle it in the database, what will the UI look like?  Will `hosts` become children of `playbooks`?

**Comment by dmsimard** [comment]
Yup, that's a good point. Different servers can have the same name. Just the same playbook ran on two different hosts referring to "localhost" as a unique host is already wrong .. and that server will have different facts, too.

Hmm. I'll do some thinking.

**Comment by dmsimard** [comment]
I think we can close this with the recent merges.
