### ISSUE TITLE
Deprecation Warning: flask.ext.sqlachemy._compat

### ISSUE THREAD

**Issue by bpereto** [dmsimard/ara#112]
Use of ara with version `0.12.1` gives me a deprecation warning:
```
/usr/local/ara/.venv/lib/python2.7/site-packages/flask/exthook.py:71: ExtDeprecationWarning: Importing flask.ext.sqlalchemy is deprecated, use flask_sqlalchemy instead.
  .format(x=modname), ExtDeprecationWarning
/usr/local/ara/.venv/lib/python2.7/site-packages/flask/exthook.py:71: ExtDeprecationWarning: Importing flask.ext.sqlalchemy._compat is deprecated, use flask_sqlalchemy._compat instead.
  .format(x=modname), ExtDeprecationWarning
```

Versions:
```
/usr/local/ara/.venv/bin/pip freeze | grep -iE 'flask|sqlalchemy'
Flask==0.11.1
Flask-Migrate==2.0.0
Flask-Script==2.0.5
Flask-SQLAlchemy==2.0
Frozen-Flask==0.13
SQLAlchemy==0.9.8
```

**Comment by dmsimard** [comment]
@bpereto Thanks for reporting, I'll have a look.

**Comment by dmsimard** [comment]
@bpereto I'm unable to reproduce on a fresh installation -- is ARA installed side-by-side another application that perhaps has lower boundaries ?

Here's what a fresh installation yields for me (note the higher versions for flask-migrate, flask-sqlalchemy and sqlalchemy):
```
$ pip freeze | grep -iE 'flask|sqlalchemy'
Flask==0.11.1
Flask-Migrate==2.0.3
Flask-Script==2.0.5
Flask-SQLAlchemy==2.2
Frozen-Flask==0.13
SQLAlchemy==1.1.6
```

**Comment by bpereto** [comment]
@dmsimard 
Yes you are right, on a fresh installation the problem doesn't exist.
I have a semi isolated virtualenv (with system site packages) because there are some python modules on RHEL 7, but mostly older version than ara expects.

I don't want to put ansible into the virtualenv, because I don't want to maintain the ara virtualenv, and the ansible server version.
The ARA is in my environment on another server than ansible runs.

**Comment by dmsimard** [comment]
@bpereto So my understanding is that the deprecation notice is not driven out of ARA usage of flask-sqlalchemy but rather from the interaction between flask and flask-sqlalchemy/flask-migrate.
We don't import ``flask.ext.sqlalchemy`` anywhere in ARA and thus there is nothing I can do about it.

Sorry.
