### ISSUE TITLE
which one is the actual repo?

### ISSUE THREAD

**Issue by COLABORATI** [dmsimard/ara#120]
There is a repo in the title that has also ara code - which one is the actual repo I should use?

**Comment by dmsimard** [comment]
@COLABORATI This is sort of a mirror -- the real repository is at https://github.com/openstack/ara

**Comment by COLABORATI** [comment]
Thanks for the info - I would like to suggest to put that info somewhere here, have a nice day!

**Comment by dmsimard** [comment]
@COLABORATI thanks I've added a description at the top to explain the purpose of this repo.
