### ISSUE TITLE
Distinguish a dry-run and a real run

### ISSUE THREAD

**Issue by thangola** [dmsimard/ara#123]
Without a look at check parameter in paremeters list, we cant know if it's a dry-run. Can we somehow make this easier?
E.g: Mark the dry-run with an icon, or change the color of date/time or something like that.

**Comment by dmsimard** [comment]
If we're able to tell if it is a dry run through the parameters we're able to identify such runs accordingly. Should be easy. Thanks for the suggestion.

**Comment by thangola** [comment]
Actually, it's even better if we have an ara parameter, that bypass the runs with `--check`. We run check quite often, and they often contain error. It's a bit noisy to submit them all to the database.
What do you think?

**Comment by dmsimard** [comment]
Sure, it can be parameterized but I would default the setting to true so --check runs are saved by default.

**Comment by dmsimard** [comment]
By the way, this is part of the things I want to do before releasing ARA 1.0 which I am working on in the following weeks.

**Comment by dmsimard** [comment]
Going to close this since it's tracked here already: https://storyboard.openstack.org/#!/story/2000929

It should still be part of 1.0 if all goes according to plan.
