### ISSUE TITLE
simplify ARA installation into ansible

### ISSUE THREAD

**Issue by ssbarnea** [dmsimard/ara#125]
I raise an feature request for [Ansible to support plugin autodiscovery](https://github.com/ansible/ansible/issues/28384) so we would not be forced to alter `ansible.cfg` file with hardcoded paths.

Lets work with Ansible team on sorting this and have ARA the first Ansible extension that only needs `pip install ara`, nothing more.

**Comment by dmsimard** [comment]
Issues for ARA are not tracked here, this repository is only kept for historical purposes.
I'll close this since it's already tracked upstream.

If necessary, could you open it here please: https://storyboard.openstack.org/#!/project/843
