### ISSUE TITLE
Commit database inserts as they are required (and think about failure tolerance)

### ISSUE THREAD

**Issue by dmsimard** [dmsimard/ara#13]
Right now the callback only commits the inserts when the playbook stats are printed.

This means a whole playbook run could not be recorded if the playbook is interrupted abnormally.
If the playbook is interrupted abnormally, we could have incomplete records (i.e, orphan records or no stats for a playbook run).

Have to this about how to handle this.

**Comment by larsks** [comment]
I would just commit after each task completes.  Again, I don't think database performance is going to be the bottleneck during an ansible run.

**Comment by dmsimard** [comment]
Fixed by https://github.com/dmsimard/ara/commit/81b87a34fa2488191d1a6abed9a639156c555fd6
