### ISSUE TITLE
Reconsider sqlite or add support for a different database backend ?

### ISSUE THREAD

**Issue by dmsimard** [dmsimard/ara#15]
sqlite was great for developing and prototyping ARA. It has little requirements, is fast at low volumes and can be used out of the box without having to install and configure a mysql server.

sqlite for the aggregated version of the interface will not scale very well.
sqlite could remain fairly performant for single run browsing. Otherwise, it will eventually crawl under the amount of records. We'd certainly have to implement pagination when browsing a large amount of data (see https://github.com/dmsimard/ara/issues/14 ). Some form of sharding could also be implemented.

MySQL could be a fairly easy target (sqlalchemy was chosen on purpose to have a relative flexibility) but then how do we send aggregated records to the database ? Do we want the callback to do inserts remotely direcly over the internet (i.e, as opposed to "concatenating" sqlite databases after the run is complete).

**Comment by larsks** [comment]
Since you're using sqlalchemy, this is just a configuration option, right?  You can load a database uri from the ansible configuration and let sqlalchemy Just Work.  See, e.g., https://github.com/larsks/example-for-dmsimard/blob/master/sql_logger.py#L40

**Comment by larsks** [comment]
I wouldn't worry about the insert performance; I think ansible execution is going to be your bottleneck, not database updates.

**Comment by dmsimard** [comment]
First party support for MySQL, otherwise sqlite will be pretty good. Closing with https://github.com/dmsimard/ara/commit/610c4e18d69fcab167bc4967379e9dbe9d9c20af
