### ISSUE TITLE
Need to better manage nested results (i.e, with items)

### ISSUE THREAD

**Issue by dmsimard** [dmsimard/ara#35]
See screenshots:
![Alt text](http://i.imgur.com/IvSXAgP.png)
![Alt text](http://i.imgur.com/6wGFmrw.png)

Maybe we can leverage the work that was done in human_log to reformat the output ?
https://github.com/redhat-openstack/weirdo/blob/master/playbooks/library/human_log.py#L39

**Comment by dmsimard** [comment]
Database with that kind of output to reproduce [ansible.sqlite.zip](https://github.com/dmsimard/ara/files/265455/ansible.sqlite.zip)

**Comment by larsks** [comment]
How about that?
