### ISSUE TITLE
Database versioning

### ISSUE THREAD

**Issue by larsks** [dmsimard/ara#43]
We should investigate a mechanism for handling database migrations (e.g., alembic or similar) so that we can preserve data when modifying the database schema.

**Comment by dmsimard** [comment]
Agreed +1

**Comment by dmsimard** [comment]
@larsks I think I remember you had a PR for initial alembic support but I can't find it (or my memory might just be failing). If you can't find it it's no big deal but I just thought I'd love to have the reference here for the record.

I moved this to StoryBoard here: https://storyboard.openstack.org/#!/story/2000751
