### ISSUE TITLE
Storing git commit hash from run as well

### ISSUE THREAD

**Issue by asmartin** [dmsimard/ara#52]
In many cases, ansible playbooks are stored in git repositories. It would be useful to have ARA store the last commit hash in the repository in its database whenever a playbook is ran. This way, you can know which specific commit produced those exact results. For example, if you have a run from 1 month ago that completed with no errors, but you encounter errors with the current version of the code, you could easily go back and see when the last successful run was. Yes, you could also figure this out with git bisect, but having this data in ARA would make it faster and easier

**Comment by larsks** [comment]
The problem, of course, is that people also manage their playbooks with things other than git.  So maybe what we want is the ability to collect the output from an arbitrary "get revision id" command.  That shouldn't be too difficult to implement.  It would probably need to go into the `v2_playbook_on_start` method.

**Comment by asmartin** [comment]
Yeah that makes sense to me, then you can customize that to be `git log` or whatever your system uses

**Comment by asmartin** [comment]
Any updates on this? I would really like to test out ARA but this feature is pretty critical to my environment.

**Comment by dmsimard** [comment]
@asmartin We haven't implemented some sort of git support as is (yet) but we now store files (and their contents). While I understand this might not be the exact thing you are looking for, this effectively means you can look at a file's contents for a particular run and a file's contents for another run.

In the UI, the files are accessible from the playbook summary view ([example](http://46.231.133.111/playbook/4c71a8c4-96d3-40ef-bf0f-20a79de413ae/)) by clicking on the [file name](http://46.231.133.111/file/974d2a0c-4130-4871-9839-2492fd7d7c1e/) or clicking on the [line number](http://46.231.133.111/file/974d2a0c-4130-4871-9839-2492fd7d7c1e/#line-19) (which highlights that particular action)

We have no "diff" mechanisms in place right now but it would be great to be able to do it someday.

Does this help you in your use case ?

**Comment by asmartin** [comment]
Could I add a local_action that calls "git rev-parse HEAD" as a task at the
beginning of my playbook and have it record the output of the command
(which would contain the hash)? That might be an easy workaround for this

**Comment by dmsimard** [comment]
@asmartin Yes, that would work. The output would be available in the task details, like [this](http://46.231.133.111/result/35ab4f8f-c697-41da-9b4b-31ce4593f1f3/).

**Comment by dmsimard** [comment]
@asmartin Hi! Another user of ARA gave me feedback on a feature he'd like to see and I believe it could fit your use case, I've documented the feature (and your example) here: https://storyboard.openstack.org/#!/story/2000755

We're migrating from github issues to storyboard for tracking. So I'll close this now and reference this issue.

Thanks and let me know if you have any questions !

**Comment by dmsimard** [comment]
@asmartin the code for the new feature is current in review, you can look at it here: https://review.openstack.org/#/q/topic:ara_record

I've actually added your use case as a working example in the documentation: https://review.openstack.org/#/c/391563/10/doc/source/usage.rst

**Comment by asmartin** [comment]
@dmsimard - thanks, this looks perfect! This provides exactly the functionality I was looking for - I'll watch for it in a future ARA release (once the review is complete)
