### ISSUE TITLE
Handle exception in playbook show

### ISSUE THREAD

**Issue by dmsimard** [dmsimard/ara#93]
╰─> $ ara playbook show blah
'NoneType' object has no attribute 'id'

Same issue as https://github.com/dmsimard/ara/issues/91

**Comment by dmsimard** [comment]
host show too.

**Comment by dmsimard** [comment]
stats show too.

**Comment by dmsimard** [comment]
task show too :P

**Comment by dmsimard** [comment]
Ok, all of them.

**Comment by larsks** [comment]
The above pr fixes the immediate problem , but in order to make this more testable we may want to raise a custom exception (`ara.exc.ResourceNotFound` or something like that), because then we can test for that trivially in our unit tests.

**Comment by dmsimard** [comment]
Closed via https://github.com/dmsimard/ara/commit/5598663fc4f91356468807fd11b59bfc9273cc08
